import { ROLES } from "./roles";

export const PERMISSIONS = {
  AGENDA_MANAGE: [
    ROLES.ADMIN,
    ROLES.KEPALA,
    ROLES.SEKRETARIS,
    ROLES.KETUA_PROGRAM_STUDI,
    ROLES.REKTOR_UNIVERSITAS_TRILOGI,
    ROLES.WAKIL_REKTOR_BIDANG_PEMBELAJARAN_DAN_KEMAHASISWAAN,
    ROLES.WAKIL_REKTOR_BIDANG_SUMBER_DAYA_DAN_KERJA_SAMA,
    ROLES.KEPALA_BAGIAN_AKREDITASI,
    ROLES.KEPALA_BAGIAN_DATA_DAN_INFORMASI,
    ROLES.KEPALA_BAGIAN_MONITORING_EVALUASI_DAN_AUDIT,
    ROLES.KEPALA_BAGIAN_PENELITIAN,
    ROLES.KEPALA_BAGIAN_PENGABDIAN_KEPADA_MASYARAKAT,
    ROLES.KEPALA_BIRO_KOMISI_ETIKA_HUKUM_DAN_KEPUTUTAN,
    ROLES.KEPALA_BIRO_SEKRETARIAT_HUMAS_DAN_PROTOKOLER,
    ROLES.KEPALA_LEMBAGA_PENELITIAN_DAN_PENGABDIAN_KEPADA_MASYARAKAT,
    ROLES.KEPALA_LEMBAGA_PENJAMINAN_MUTU,
    ROLES.SEKRETARIS_LPM,
  ],

  AGENDA_VIEW: [ROLES.STAFF, ROLES.STAFF_LPM, ROLES.DOSEN],
};
