export const ROLES = {
  STAFF: "Staff",
  DOSEN: "Dosen",
  ADMIN: "Admin",
  KEPALA: "Kepala",
  SEKRETARIS: "Sekretaris",
  KETUA_PROGRAM_STUDI: "Ketua Program Studi",
  REKTOR_UNIVERSITAS_TRILOGI: "Rektor Universitas Trilogi",
  WAKIL_REKTOR_BIDANG_PEMBELAJARAN_DAN_KEMAHASISWAAN: "Wakil Rektor Bidang Pembelajaran dan Kemahasiswaan",
  WAKIL_REKTOR_BIDANG_SUMBER_DAYA_DAN_KERJA_SAMA: "Wakil Rektor Bidang Sumber Daya dan Kerja Sama",
  KEPALA_BIRO_KOMISI_ETIKA_HUKUM_DAN_KEPUTUTAN: "Wakil Biro Komisi Etika, Hukum dan Kepututan",
  KEPALA_BIRO_SEKRETARIAT_HUMAS_DAN_PROTOKOLER: "kepala Biro Sekretariat, Humas dan Protokoler",
  KEPALA_LEMBAGA_PENELITIAN_DAN_PENGABDIAN_KEPADA_MASYARAKAT: "Kepala Lemabaga Penelitian dan Pengabdian Kepada Masyarakat",
  KEPALA_BAGIAN_PENELITIAN: "Kepala Bagian Penelitian",
  SEKRETARIS_LPM: "Sekretaris LPM",
  KEPALA_BAGIAN_PENGABDIAN_KEPADA_MASYARAKAT: "Kepala Bagian Pengabdian Kepada Masyarakat",
  KEPALA_LEMBAGA_PENJAMINAN_MUTU: "Kepala Lembaga Penjaminan Mutu",
  KEPALA_BAGIAN_DATA_DAN_INFORMASI: "Kepala Bagian Data dan Informasi",
  KEPALA_BAGIAN_MONITORING_EVALUASI_DAN_AUDIT: "Kepala Bagian Monitoring, Evaluasi dan Audit",
  KEPALA_BAGIAN_AKREDITASI: "Kepala Bagian Akreditasi",
  STAFF_LPM: "Staff LPM",
};
